const Data = [
    {
        id: 1,
        title: "Iphone 14/14plus",
        img: "mo1.jpeg",
        price: "Just 35000/-",
        category: "Electronic",
    },
    {
        id: 2,
        title: "Vivo T1",
        img: "mo4.jpeg",
        price: "Just 35000/-",
        category: "Mobiles",
    },
    {
        id: 3,
        title: "Moto E13",
        img: "mo3.jpeg",
        price: "Just 35000/-",
        category: "Fashion",
    },
    {
        id: 4,
        title: "Infinix Hot 10s",
        img: "mo2.jpeg",
        price: "Just 35000/-",
        category: "Home",
    },
    {
        id: 5,
        title: "Infinix Hot 10s",
        img: "mo2.jpeg",
        price: "Just 35000/-",
        category: "Grocery",
    },
    {
        id: 6,
        title: "Iphone 14/14plus",
        img: "mo1.jpeg",
        price: "Just 35000/-",
        category: "Electronic",
    },
    {
        id: 7,
        title: "Vivo T1",
        img: "mo4.jpeg",
        price: "Just 35000/-",
        category: "Mobiles",
    },
    {
        id: 8,
        title: "Moto E13",
        img: "wa1.jpeg",
        price: "Just 35000/-",
        category: "Fashion",
    },
    {
        id: 9,
        title: "Infinix Hot 10s",
        img: "mo2.jpeg",
        price: "Just 35000/-",
        category: "Home",
    },
    {
        id: 10,
        title: "Infinix Hot 10s",
        img: "mo2.jpeg",
        price: "Just 35000/-",
        category: "Grocery",
    },
    {
        id: 11,
        title: "Infinix Hot 10s",
        img: "mo2.jpeg",
        price: "Just 35000/-",
        category: "Home",
    },
    {
        id: 12,
        title: "Infinix Hot 10s",
        img: "mo2.jpeg",
        price: "Just 35000/-",
        category: "Grocery",
    },
  ]
  export default Data